// Données partagées entre carnet-de-mots.html et focus.html.
// Ce fichier est chargé comme <script src> classique (pas de module), donc ces
// var deviennent globales et sont lues par les deux pages.

  var BASE_ENTRIES = [
    { mot: "s’évertuer", emoji: "💪", type: "verbe",
      def: "Faire des efforts soutenus, avec insistance, pour parvenir à un résultat — souvent sans y parvenir.",
      ex: "Elle <strong>s’évertue</strong> à réparer cette vieille horloge depuis trois week-ends.",
      syn: "s’acharner, s’échiner, se démener, s’obstiner" },
    { mot: "extatique", emoji: "🤩", type: "adjectif",
      def: "Qui est plongé dans un état d’extase, de ravissement total, comme suspendu hors de soi.",
      ex: "Il est resté <strong>extatique</strong> devant la fresque, incapable de détourner le regard.",
      syn: "ravi, transporté, en extase, émerveillé" },
    { mot: "les quatre cavaliers de l’apocalypse", emoji: "🐎", type: "expression",
      def: "Référence biblique (Apocalypse de Jean) à quatre figures montées à cheval — Conquête, Guerre, Famine, Mort — annonçant la fin des temps. Par extension : quatre fléaux ou événements catastrophiques qui surviennent ensemble.",
      ex: "Inflation, sécheresse, pénurie d’énergie et grève générale : on aurait dit les <strong>quatre cavaliers de l’apocalypse</strong> s’abattre sur le pays la même semaine.",
      syn: "fléaux conjugués, catastrophes annonciatrices, présages funèstes" },
    { mot: "montrer patte blanche", emoji: "🐾", type: "expression",
      def: "Prouver son identité, sa légitimité ou sa bonne foi pour être admis quelque part — comme le loup qui, dans la fable, doit montrer patte blanche pour qu’on lui ouvre.",
      ex: "Pour accéder aux archives, il faut <strong>montrer patte blanche</strong> : badge, pièce d’identité et autorisation signée.",
      syn: "donner des gages, prouver sa légitimité, se faire reconnaître" },
    { mot: "cathartique", emoji: "🌩️", type: "adjectif",
      def: "Qui procûre une catharsis — qui libère, purge ou soulage d’une tension émotionnelle accumulée.",
      ex: "Ce concert improvisé après l’annonce a été <strong>cathartique</strong> pour toute la salle.",
      syn: "libérateur, purgatif, exutoire, salutaire" },
    { mot: "émulation", emoji: "🔥", type: "nom",
      def: "Stimulation positive née de la comparaison ou de la compétition avec autrui, qui pousse chacun à se dépasser.",
      ex: "La rivalité amicale entre les deux ateliers crée une belle <strong>émulation</strong>.",
      syn: "stimulation, entraînement mutuel, rivalité stimulante" },
    { mot: "j’ai coutume de dire", emoji: "🗣️", type: "expression",
      def: "Formule introductive signifiant « j’ai l’habitude de dire », employée pour présenter une maxime ou une réflexion personnelle récurrente.",
      ex: "<strong>J’ai coutume de dire</strong> que mieux vaut une vérité qui dérange qu’un silence confortable.",
      syn: "j’ai pour habitude de dire, comme je le dis souvent" },
    { mot: "sous l’égide de", emoji: "🛡️", type: "expression",
      def: "Sous la protection, l’autorité morale ou le patronage de quelqu’un ou d’une institution.",
      ex: "Le colloque s’est tenu <strong>sous l’égide de</strong> l’UNESCO.",
      syn: "sous l’autorité de, sous le patronage de, sous la houlette de" },
    { mot: "déguerpir", emoji: "🏃", type: "verbe",
      def: "Partir précipitamment, quitter les lieux en toute hâte — souvent sous la contrainte ou la peur.",
      ex: "À l’arrivée du propriétaire, les squatteurs ont <strong>déguerpi</strong> sans demander leur reste.",
      syn: "s’enfuir, filer, décamper, détaler" },
    { mot: "velléité", emoji: "💭", type: "nom",
      def: "Intention ou désir faible, hésitant, qui ne se concrétise presque jamais en action.",
      ex: "Il a eu quelques <strong>velléités</strong> de reprendre le sport en janvier, vite oubliées en février.",
      syn: "intention vague, hésitation, désir passager" },
    { mot: "illusoire", emoji: "🌫️", type: "adjectif",
      def: "Qui n’a que l’apparence de la réalité, trompeur, sans fondement solide — voué à décevoir.",
      ex: "L’espoir d’un accord conclu en un jour s’est vite révélé <strong>illusoire</strong>.",
      syn: "trompeur, fictif, chimérique, vain" },
    { mot: "cossu", emoji: "🏛️", type: "adjectif",
      def: "Qui révèle l’aisance matérielle, la richesse — se dit d’un lieu, d’un intérieur ou d’une allure.",
      ex: "Ils ont grandi dans un quartier <strong>cossu</strong>, aux façades haussmanniennes bien entretenues.",
      syn: "riche, opulent, aisé, huppé, fortuné" },
    { mot: "inexorable", emoji: "🌊", type: "adjectif",
      def: "Qu’on ne peut ni arrêter, ni fléchir, ni attendrir — implacable dans son déroulement.",
      ex: "Malgré les efforts de l’équipe, le déclin du magasin semblait <strong>inexorable</strong>.",
      syn: "implacable, inéluctable, imparable, impitoyable" },
    { mot: "inéluctable", emoji: "♟️", type: "adjectif",
      def: "Qui ne peut être évité ni empêché — dont l’issue est certaine.",
      ex: "Face à l’accumulation des signes, la rupture paraissait <strong>inéluctable</strong>.",
      syn: "inévitable, fatal, certain, inexorable" },
    { mot: "incommensurable", emoji: "♾️", type: "adjectif",
      def: "Si grand, si vaste qu’il échappe à toute mesure ou comparaison.",
      ex: "L’écart de moyens entre les deux candidats était <strong>incommensurable</strong>.",
      syn: "immense, infini, considérable, sans commune mesure" },
    { mot: "dans la mesure où", emoji: "⚖️", type: "expression",
      def: "Introduit une cause ou une condition : « étant donné que », « pour autant que ».",
      ex: "<strong>Dans la mesure où</strong> vous respectez le délai, aucune pénalité ne sera appliquée.",
      syn: "étant donné que, puisque, pour autant que, dès lors que" },
    { mot: "Kevin", emoji: "🏷️", type: "anecdote",
      def: "Après le succès du film américain <em>Maman, j’ai raté l’avion</em> et de son héros Kevin McCallister, le prénom connaît un pic de popularité en France à la fin des années 1980 et dans les années 1990. Il devient ensuite, de façon assez injuste, la cible d’une stigmatisation sociale : le sociologue Baptiste Coulmont a documenté cet « effet Kevin », montrant comment un prénom peut se retrouver associé à des préjugés de classe sociale, sans rapport avec la personne qui le porte.",
      ex: "Ce biais social, qu’on surnomme parfois l’effet <strong>Kevin</strong>, a été mis au jour par le sociologue Baptiste Coulmont.",
      syn: "stigmatisation par le prénom, effet de classe, travaux de Baptiste Coulmont" },
    { mot: "tête de linotte", emoji: "🐦", type: "expression",
      def: "Personne étourdie, distraite, qui oublie tout et manque de constance dans ses pensées.",
      ex: "J’ai encore laissé mes clés à l’intérieur, quelle <strong>tête de linotte</strong> je fais !",
      syn: "étourdi, écervelé, distrait, tête en l’air" },
    { mot: "facétieux", emoji: "😏", type: "adjectif",
      def: "Qui aime plaisanter, faire des farces avec espièglerie — d’un esprit taquin et léger.",
      ex: "D’un ton <strong>facétieux</strong>, il a glissé une fausse note dans le rapport pour voir qui la remarquerait.",
      syn: "farceur, espiègle, taquin, malicieux" },
    { mot: "à telle enseigne que", emoji: "🪧", type: "expression",
      def: "Introduit une conséquence qui vient confirmer ce qui précède : « à tel point que », « si bien que ».",
      ex: "Il ne supportait plus le bruit, <strong>à telle enseigne qu’</strong>il a fini par déménager à la campagne.",
      syn: "à tel point que, si bien que, tant et si bien que" },
    { mot: "en lieu et place de", emoji: "🔁", type: "expression",
      def: "À la place de, en remplacement de — souvent dans un contexte officiel ou formel.",
      ex: "Le directeur adjoint a signé les contrats <strong>en lieu et place du</strong> directeur, retenu à l’étranger.",
      syn: "à la place de, au lieu de, en remplacement de" },
    { mot: "c’est de la monnaie de singe", emoji: "🐒", type: "expression",
      def: "Se dit d’une compensation ou d’une promesse sans valeur réelle, qui ne coûte rien à celui qui la donne.",
      ex: "Des félicitations sans augmentation, <strong>c’est de la monnaie de singe</strong>.",
      syn: "fausse monnaie, paroles en l’air, compensation illusoire" },
    { mot: "élucubration", emoji: "🌀", type: "nom",
      def: "Idée ou théorie extravagante, peu sérieuse, souvent élaborée avec effort mais sans fondement solide.",
      ex: "Personne ne prend au sérieux sa dernière <strong>élucubration</strong> sur le sujet.",
      syn: "divagation, fumisterie, théorie fumeuse" },
    { mot: "faire du zèle", emoji: "🙋", type: "expression",
      def: "En faire plus que nécessaire, avec un empressement parfois excessif ou mal vu.",
      ex: "Il a voulu <strong>faire du zèle</strong> devant sa hiérarchie et a fini par agacer toute l’équipe.",
      syn: "en rajouter, se surpasser à l’excès, jouer les bons élèves" },
    { mot: "écueil", emoji: "🪨", type: "nom",
      def: "Obstacle caché, difficulté qu’on risque de heurter sans l’avoir anticipée.",
      ex: "Le principal <strong>écueil</strong> du projet a été sous-estimé dès le départ.",
      syn: "obstacle, piège, difficulté" },
    { mot: "ésotérique", emoji: "🔮", type: "adjectif",
      def: "Réservé à des initiés, difficile d’accès pour qui n’en possède pas les clés.",
      ex: "Son jargon technique reste totalement <strong>ésotérique</strong> pour les non-spécialistes.",
      syn: "hermétique, obscur, initiatique" },
    { mot: "on fait de la dentelle fine", emoji: "🧵", type: "expression",
      def: "Travailler avec une précision et un soin extrêmes, sur des détails délicats.",
      ex: "Sur ce dossier sensible, <strong>on fait de la dentelle fine</strong>, chaque mot compte.",
      syn: "travail de précision, de l’orfèvrerie, du sur-mesure" },
    { mot: "éperdument", emoji: "💘", type: "adverbe",
      def: "Avec une intensité extrême, sans retenue, souvent en parlant d’un sentiment.",
      ex: "Il est tombé <strong>éperdument</strong> amoureux dès leur première rencontre.",
      syn: "follement, passionnément, à la folie" },
    { mot: "grands marronniers", emoji: "🌰", type: "nom",
      def: "Sujets journalistiques récurrents qu’on ressort chaque année, par tradition plus que par actualité.",
      ex: "L’article sur les résolutions de janvier est un des grands <strong>marronniers</strong> de la presse.",
      syn: "sujet récurrent, serpent de mer médiatique, classique saisonnier" },
    { mot: "prolifique", emoji: "🌱", type: "adjectif",
      def: "Qui produit en abondance, avec une grande fécondité créative ou biologique.",
      ex: "Cet auteur <strong>prolifique</strong> publie presque un roman par an.",
      syn: "fécond, productif, abondant" },
    { mot: "volubile", emoji: "🗨️", type: "adjectif",
      def: "Qui parle avec une abondance et une facilité remarquables, parfois sans s’arrêter.",
      ex: "Elle est restée <strong>volubile</strong> pendant tout le dîner, sans laisser un blanc.",
      syn: "bavard, loquace, intarissable" },
    { mot: "élément de langage", emoji: "🎙️", type: "expression",
      def: "Formule préparée à l’avance, souvent par la communication politique ou d’entreprise, pour orienter le discours.",
      ex: "Ce n’est pas une réponse, c’est un <strong>élément de langage</strong> répété mot pour mot.",
      syn: "formule toute faite, discours préparé, ligne de communication" },
    { mot: "c’est le fer de lance", emoji: "🗡️", type: "expression",
      def: "Se dit de ce qui représente la pointe avancée, le symbole ou le moteur principal d’une action.",
      ex: "Ce produit est le <strong>fer de lance</strong> de leur stratégie à l’international.",
      syn: "locomotive, porte-drapeau, tête de proue" },
    { mot: "gravé dans le marbre", emoji: "🪦", type: "expression",
      def: "Définitivement fixé, immuable, qu’on ne peut plus remettre en question.",
      ex: "Ce calendrier n’est pas <strong>gravé dans le marbre</strong>, il peut encore évoluer.",
      syn: "figé, immuable, définitif" },
    { mot: "univoque", emoji: "🎯", type: "adjectif",
      def: "Qui n’a qu’un seul sens possible, sans ambiguïté d’interprétation.",
      ex: "Sa réponse était <strong>univoque</strong> : ce sera non, sans condition.",
      syn: "sans ambiguïté, clair, à sens unique" },
    { mot: "de façon incrémentale", emoji: "🧱", type: "expression",
      def: "Par petites étapes successives, plutôt que par un changement brutal et global.",
      ex: "L’équipe a préféré avancer <strong>de façon incrémentale</strong> plutôt que de tout refondre d’un coup.",
      syn: "progressivement, par paliers, pas à pas" },
    { mot: "retrousser nos manches", emoji: "💪", type: "expression",
      def: "Se mettre activement au travail, avec détermination, souvent après une période d’hésitation.",
      ex: "Il est temps de <strong>retrousser nos manches</strong> pour rattraper le retard.",
      syn: "se mettre au travail, s’atteler à la tâche, passer à l’action" },
    { mot: "stakhanoviste", emoji: "🏭", type: "nom",
      def: "Personne qui travaille avec un zèle acharné, presque excessif, jusqu’à l’exemplarité.",
      ex: "Ce <strong>stakhanoviste</strong> enchaîne les heures supplémentaires sans jamais se plaindre.",
      syn: "travailleur acharné, bourreau de travail, forcené du boulot" },
    { mot: "se recroqueviller", emoji: "🥶", type: "verbe",
      def: "Se replier sur soi-même, se ramasser en une position réduite, souvent par froid ou par peur.",
      ex: "Le chat s’est <strong>recroquevillé</strong> dans le coin le plus chaud de la pièce.",
      syn: "se replier, se blottir, se ratatiner" },
    { mot: "il est au four et au moulin", emoji: "🍞", type: "expression",
      def: "Se dit de quelqu’un qui doit s’occuper de plusieurs tâches à la fois, sur des fronts différents.",
      ex: "Entre les clients et les livraisons, il est <strong>au four et au moulin</strong> toute la journée.",
      syn: "être sur tous les fronts, courir partout, multiplier les casquettes" },
    { mot: "en dilettante", emoji: "🎨", type: "expression",
      def: "En amateur, par plaisir, sans engagement professionnel ni rigueur systématique.",
      ex: "Il pratique la peinture <strong>en dilettante</strong>, sans jamais viser l’exposition.",
      syn: "en amateur, par loisir, sans y consacrer sa vie" },
    { mot: "je te donne le dessous des cartes", emoji: "🃏", type: "expression",
      def: "Révéler les informations ou mécanismes cachés derrière une situation, ce qui ne se voit pas de l’extérieur.",
      ex: "Laisse-moi te donner le <strong>dessous des cartes</strong> avant que tu ne signes quoi que ce soit.",
      syn: "révéler les coulisses, dévoiler l’envers du décor, donner la clé" },
    { mot: "virevolter", emoji: "🌀", type: "verbe",
      def: "Tourner rapidement sur soi-même ou se déplacer avec vivacité et légèreté en tous sens.",
      ex: "Les feuilles mortes <strong>virevoltaient</strong> dans le vent d’automne.",
      syn: "tournoyer, voltiger, tourbillonner" },
    { mot: "chemin de croix", emoji: "✝️", type: "expression",
      def: "Épreuve longue et douloureuse, faite d’obstacles successifs, par référence à la Passion du Christ.",
      ex: "Obtenir ce visa a été un véritable <strong>chemin de croix</strong> administratif.",
      syn: "calvaire, parcours du combattant, épreuve douloureuse" },
    { mot: "clé de lecture", emoji: "🔑", type: "expression",
      def: "Élément ou grille d’interprétation qui permet de comprendre un fait ou une œuvre sous un certain angle.",
      ex: "Cette <strong>clé de lecture</strong> historique change complètement le sens du texte.",
      syn: "grille d’interprétation, angle d’analyse, prisme" },
    { mot: "avoir le vent en poupe", emoji: "⛵", type: "expression",
      def: "Connaître une période de succès, être porté par une dynamique favorable.",
      ex: "Depuis sa dernière campagne, la marque a le <strong>vent en poupe</strong>.",
      syn: "être en plein essor, avoir la cote, être sur une dynamique positive" },
    { mot: "question de béotien / néophyte", emoji: "🙋‍♂️", type: "expression",
      def: "Question posée par quelqu’un qui découvre un sujet, sans connaissances préalables — parfois par fausse modestie avant une question pointue.",
      ex: "Question de <strong>béotien</strong> : à quoi sert exactement ce paramètre ?",
      syn: "question de débutant, question naïve, question de néophyte" },
    { mot: "élargir la fenêtre d’Overton", emoji: "🪟", type: "expression",
      def: "Repousser les limites de ce qui est considéré comme acceptable dans le débat public, souvent en normalisant des propos autrefois marginaux.",
      ex: "Certains discours extrêmes servent surtout à <strong>élargir la fenêtre d’Overton</strong> pour rendre la position suivante plus acceptable.",
      syn: "déplacer le curseur du débat, normaliser l’extrême, repousser les limites acceptables" },
    { mot: "homérique", emoji: "⚔️", type: "adjectif",
      def: "D’une ampleur ou d’une intensité épique, digne des récits d’Homère.",
      ex: "La réunion s’est terminée par une dispute <strong>homérique</strong> entre les deux associés.",
      syn: "épique, titanesque, mémorable" },
    { mot: "être dans l’œil du cyclone", emoji: "🌀", type: "expression",
      def: "Être au centre d’une situation agitée, parfois dans une accalmie trompeuse au milieu du chaos environnant.",
      ex: "L’entreprise est actuellement dans l’<strong>œil du cyclone</strong> médiatique.",
      syn: "être au cœur de la tempête, être au centre de l’agitation, être sous le feu des projecteurs" },
    { mot: "c’est le baptême du feu", emoji: "🔥", type: "expression",
      def: "Se dit d’une première épreuve difficile, souvent formatrice, à laquelle on est confronté sans préparation suffisante.",
      ex: "Pour sa première présentation client, ce fut un vrai <strong>baptême du feu</strong>.",
      syn: "première épreuve, épreuve initiatique, entrée en matière difficile" },
    { mot: "plaidoyer", emoji: "⚖️", type: "nom",
      def: "Discours argumenté en faveur d’une cause ou d’une personne, cherchant à convaincre.",
      ex: "Son intervention était un véritable <strong>plaidoyer</strong> pour le télétravail.",
      syn: "défense argumentée, argumentaire, plaidoirie" },
    { mot: "taciturne", emoji: "🤐", type: "adjectif",
      def: "Qui parle peu, par nature ou par disposition, souvent perçu comme renfermé.",
      ex: "Son collègue <strong>taciturne</strong> ne prend presque jamais la parole en réunion.",
      syn: "silencieux, renfermé, peu loquace" },
    { mot: "être tributaire", emoji: "⛓️", type: "expression",
      def: "Dépendre étroitement de quelque chose ou de quelqu’un pour fonctionner ou réussir.",
      ex: "La production reste <strong>tributaire</strong> d’un seul fournisseur, ce qui est risqué.",
      syn: "dépendre de, être à la merci de, être conditionné par" },
    { mot: "c’est pas Bizance", emoji: "🏛️", type: "expression",
      def: "Se dit d’une situation modeste, loin du luxe ou de l’abondance espérée.",
      ex: "L’hôtel était propre mais <strong>c’est pas Bizance</strong>, disons-le.",
      syn: "ce n’est pas le grand luxe, rien d’extraordinaire, modeste" },
    { mot: "savonner la planche", emoji: "🧼", type: "expression",
      def: "Chercher discrètement à faire échouer ou déstabiliser quelqu’un, souvent pour l’évincer.",
      ex: "Certains collègues ont clairement essayé de lui <strong>savonner la planche</strong> avant l’entretien.",
      syn: "saboter, déstabiliser, chercher à faire trébucher" },
    { mot: "mettre du vernis", emoji: "💅", type: "expression",
      def: "Donner une apparence flatteuse et superficielle à quelque chose, sans en changer le fond.",
      ex: "Ce rapport se contente de <strong>mettre du vernis</strong> sur des résultats décevants.",
      syn: "enjoliver, embellir superficiellement, maquiller la réalité" },
    { mot: "ersatz", emoji: "🧪", type: "nom",
      def: "Substitut de moindre qualité, censé remplacer quelque chose de plus authentique ou meilleur.",
      ex: "Cette réunion en visio n’est qu’un pâle <strong>ersatz</strong> d’un vrai séminaire d’équipe.",
      syn: "succédané, substitut, imitation" },
    { mot: "être la courroie de transmission", emoji: "⚙️", type: "expression",
      def: "Servir d’intermédiaire essentiel qui relaie une information, une décision ou une énergie d’un point à un autre.",
      ex: "Le manager de proximité est souvent la <strong>courroie de transmission</strong> entre direction et terrain.",
      syn: "intermédiaire, relais, chaînon de transmission" },
    { mot: "concomitant", emoji: "⏱️", type: "adjectif",
      def: "Qui se produit en même temps qu’un autre événement, sans qu’il y ait forcément de lien de cause.",
      ex: "La hausse des prix a été <strong>concomitante</strong> à la pénurie de matières premières.",
      syn: "simultané, parallèle, coïncident" },
    { mot: "amender", emoji: "✏️", type: "verbe",
      def: "Modifier un texte ou une proposition pour l’améliorer ou en corriger certains points.",
      ex: "Les députés ont proposé d’<strong>amender</strong> l’article avant le vote final.",
      syn: "modifier, corriger, réviser" },
    { mot: "nec plus ultra", emoji: "👑", type: "expression",
      def: "Ce qui se fait de mieux dans un domaine, le sommet indépassable de la qualité.",
      ex: "Ce restaurant est considéré comme le <strong>nec plus ultra</strong> de la gastronomie locale.",
      syn: "summum, top du top, fin du fin" },
    { mot: "en l’espèce", emoji: "📋", type: "expression",
      def: "Dans le cas précis dont il est question, employé pour ramener une discussion générale à la situation concrète.",
      ex: "<strong>En l’espèce</strong>, le contrat ne prévoit aucune clause de ce type.",
      syn: "dans ce cas précis, en l’occurrence, pour ce cas particulier" },
    { mot: "jouer sa partition", emoji: "🎼", type: "expression",
      def: "Tenir son rôle dans un ensemble, apporter sa contribution spécifique à une œuvre collective.",
      ex: "Chaque service doit <strong>jouer sa partition</strong> pour que le projet aboutisse.",
      syn: "tenir son rôle, apporter sa pierre à l’édifice, faire sa part" },
    { mot: "dans le formol", emoji: "🧫", type: "expression",
      def: "Figé, conservé sans évolution, comme mis à l’écart du mouvement du reste du monde.",
      ex: "Cette procédure semble être restée <strong>dans le formol</strong> depuis vingt ans.",
      syn: "figé dans le temps, immobile, conservé tel quel" },
    { mot: "holistique", emoji: "🌐", type: "adjectif",
      def: "Qui considère un ensemble dans sa globalité plutôt que la somme isolée de ses parties.",
      ex: "L’équipe a adopté une approche <strong>holistique</strong> du bien-être au travail.",
      syn: "global, systémique, d’ensemble" },
    { mot: "à bâtons rompus", emoji: "🎙️", type: "expression",
      def: "De façon libre et informelle, en passant d’un sujet à l’autre sans plan structuré.",
      ex: "Ils ont discuté <strong>à bâtons rompus</strong> pendant tout le trajet.",
      syn: "sans plan précis, de façon décousue, librement" },
    { mot: "avoir des trous dans la raquette", emoji: "🎾", type: "expression",
      def: "Présenter des lacunes ou des oublis notables dans ses connaissances ou son organisation.",
      ex: "Sur ce dossier, il a clairement des <strong>trous dans la raquette</strong>.",
      syn: "avoir des lacunes, avoir des manques, être incomplet" },
    { mot: "corollaire", emoji: "➕", type: "nom",
      def: "Conséquence qui découle logiquement et presque automatiquement d’un fait ou d’un principe déjà établi.",
      ex: "La hausse des ventes est le <strong>corollaire</strong> direct de la nouvelle campagne.",
      syn: "conséquence, suite logique, résultante" },
    { mot: "encéphalogramme plat", emoji: "📉", type: "expression",
      def: "Se dit d’une absence totale d’activité, d’intérêt ou de réaction, par référence au tracé plat de la mort cérébrale.",
      ex: "La salle est restée d’un <strong>encéphalogramme plat</strong> pendant toute la présentation.",
      syn: "absence totale de réaction, néant, aucune activité" },
    { mot: "poncif", emoji: "📎", type: "nom",
      def: "Idée ou expression tellement répétée qu’elle a perdu toute originalité.",
      ex: "Dire que chaque échec est une leçon est devenu un vrai <strong>poncif</strong> managérial.",
      syn: "cliché, lieu commun, banalité répétée" },
    { mot: "abaque", emoji: "🧮", type: "nom",
      def: "Instrument ou tableau de calcul permettant de lire rapidement un résultat à partir de plusieurs variables.",
      ex: "L’ingénieur a utilisé un <strong>abaque</strong> pour estimer la résistance du matériau.",
      syn: "table de calcul, réglette, abaque de conversion" },
    { mot: "morceler", emoji: "🧩", type: "verbe",
      def: "Diviser un ensemble en plusieurs parties, parfois au point d’en perdre la cohérence globale.",
      ex: "Si tu <strong>morcèles</strong> trop la présentation, le message principal va se diluer.",
      syn: "fragmenter, diviser, découper" },
    { mot: "grand-banditisme", emoji: "🕵️", type: "nom",
      def: "Criminalité organisée de haut niveau, impliquant des réseaux structurés et des affaires d’envergure.",
      ex: "Cette affaire relève clairement du <strong>grand-banditisme</strong>, avec un réseau bien organisé.",
      syn: "criminalité organisée, grand crime organisé, milieu" },
    { mot: "innocuité", emoji: "🛡️", type: "nom",
      def: "Ce qui n’est pas nuisible, qui ne présente aucun danger ni effet néfaste.",
      ex: "Les tests ont confirmé l’<strong>innocuité</strong> du produit pour la peau.",
      syn: "inoffensivité, absence de danger, caractère anodin" },
    { mot: "irrévérence", emoji: "😜", type: "nom",
      def: "Attitude qui manque de respect envers ce qui est habituellement considéré comme sérieux ou sacré.",
      ex: "Son <strong>irrévérence</strong> vis-à-vis de la hiérarchie amuse autant qu’elle dérange.",
      syn: "impertinence, insolence, manque de respect" },
    { mot: "emphase", emoji: "📢", type: "nom",
      def: "Insistance excessive, ton solennel ou grandiloquent employé pour souligner un propos.",
      ex: "Il a annoncé la nouvelle avec une <strong>emphase</strong> presque théâtrale.",
      syn: "grandiloquence, solennité excessive, emphase oratoire" },
    { mot: "stricto sensu", emoji: "📏", type: "expression",
      def: "Au sens strict et rigoureux du terme, sans extension ni interprétation large.",
      ex: "<strong>Stricto sensu</strong>, ce n’est pas un mensonge, mais l’esprit du propos y ressemble.",
      syn: "au sens strict, à la lettre, rigoureusement parlant" },
    { mot: "olibrius", emoji: "🎭", type: "nom",
      def: "Personnage qui se fait remarquer de façon fâcheuse, souvent par un comportement extravagant ou ridicule.",
      ex: "Un <strong>olibrius</strong> a interrompu la cérémonie en réclamant le micro.",
      syn: "fantaisiste, énergumène, phénomène" },
    { mot: "s’amonceler", emoji: "🗑️", type: "verbe",
      def: "Former un tas en s’accumulant progressivement, au point de devenir encombrant.",
      ex: "Les dossiers en retard commencent à <strong>s’amonceler</strong> sur son bureau.",
      syn: "s’accumuler, s’entasser, s’empiler" },
    { mot: "vindicatif", emoji: "😡", type: "adjectif",
      def: "Porté à la vengeance, qui garde rancune et cherche à se venger d’un tort subi.",
      ex: "Il est resté <strong>vindicatif</strong> envers son ancien associé pendant des années.",
      syn: "rancunier, revanchard, porté à la vengeance" },
    { mot: "exutoire", emoji: "🎈", type: "nom",
      def: "Moyen de libérer une tension ou une émotion accumulée, sans rapport direct avec sa cause.",
      ex: "Le sport lui sert d’<strong>exutoire</strong> après une semaine stressante.",
      syn: "défouloir, soupape, dérivatif" },
    { mot: "ex nihilo", emoji: "✨", type: "expression",
      def: "À partir de rien, sans matériau ni base préexistante.",
      ex: "Cette entreprise a été construite <strong>ex nihilo</strong> en moins de deux ans.",
      syn: "à partir de rien, de zéro, sans rien au départ" },
    { mot: "pénultième / antépénultième", emoji: "🔢", type: "adjectif",
      def: "L’avant-dernier (pénultième) ou l’avant-avant-dernier (antépénultième) élément d’une série.",
      ex: "L’accent tombe sur la syllabe <strong>pénultième</strong> dans ce mot.",
      syn: "avant-dernier, avant-avant-dernier" },
    { mot: "phagocyter", emoji: "🦠", type: "verbe",
      def: "Absorber et faire disparaître progressivement quelque chose en l’intégrant à soi, au sens propre ou figuré.",
      ex: "Le nouveau service a fini par <strong>phagocyter</strong> les missions de l’ancienne équipe.",
      syn: "absorber, engloutir, assimiler" },
    { mot: "en bonne et due forme", emoji: "📜", type: "expression",
      def: "Selon les règles et formalités requises, de manière officielle et complète.",
      ex: "Le contrat a été signé <strong>en bonne et due forme</strong> devant témoins.",
      syn: "dans les règles, officiellement, en toute légalité" },
    { mot: "pis-aller", emoji: "🩹", type: "nom",
      def: "Solution insatisfaisante à laquelle on se résout faute de mieux.",
      ex: "Cette solution provisoire n’est qu’un <strong>pis-aller</strong> en attendant mieux.",
      syn: "solution de repli, moindre mal, palliatif temporaire" },
    { mot: "saisissant", emoji: "😲", type: "adjectif",
      def: "Se dit de ce qui frappe vivement l’esprit ou les sens, par sa force ou son contraste.",
      ex: "La ressemblance entre les deux frères est <strong>saisissante</strong>.",
      syn: "frappant, stupéfiant, impressionnant" },
    { mot: "périphrase", emoji: "🔄", type: "nom",
      def: "Expression qui désigne une chose par un détour, plutôt que par le mot exact.",
      ex: "Il a utilisé une longue <strong>périphrase</strong> pour éviter de dire clairement <em>licenciement</em>.",
      syn: "détour verbal, circonlocution, tournure indirecte" },
    { mot: "abscons", emoji: "🌫️", type: "adjectif",
      def: "Difficile à comprendre, obscur au point de sembler presque incompréhensible.",
      ex: "Son explication technique restait totalement <strong>abscons</strong>e pour le reste de l’équipe.",
      syn: "incompréhensible, hermétique, obscur" },
    { mot: "se faire un sang d’encre", emoji: "😰", type: "expression",
      def: "S’inquiéter énormément, au point d’en être physiquement affecté.",
      ex: "Elle s’est fait un <strong>sang d’encre</strong> toute la nuit avant les résultats.",
      syn: "se ronger les sangs, être très inquiet, s’angoisser" },
    { mot: "caduque", emoji: "🍂", type: "adjectif",
      def: "Qui n’est plus valable, tombé en désuétude ou expiré.",
      ex: "Cette clause du contrat est devenue <strong>caduque</strong> depuis la nouvelle loi.",
      syn: "obsolète, périmé, sans effet" },
    { mot: "méthode clé en main", emoji: "🔧", type: "expression",
      def: "Solution complète et immédiatement utilisable, ne nécessitant aucun ajustement supplémentaire.",
      ex: "L’agence propose une <strong>méthode clé en main</strong> pour lancer sa boutique en ligne.",
      syn: "solution prête à l’emploi, package complet, tout compris" },
    { mot: "manu militari", emoji: "👮", type: "expression",
      def: "Par la force, en employant la contrainte physique ou militaire si nécessaire.",
      ex: "Les squatteurs ont été évacués <strong>manu militari</strong> par les forces de l’ordre.",
      syn: "par la force, de force, sous la contrainte" },
    { mot: "dans sa tour d’ivoire", emoji: "🗼", type: "expression",
      def: "Isolé volontairement du monde réel, coupé des préoccupations concrètes des autres.",
      ex: "On lui reproche de rester dans sa <strong>tour d’ivoire</strong>, loin du terrain.",
      syn: "isolé du réel, coupé du monde, retranché" },
    { mot: "rembobiner la cassette", emoji: "📼", type: "expression",
      def: "Revenir en arrière sur des faits passés pour les réexaminer ou les raconter à nouveau.",
      ex: "Il a fallu <strong>rembobiner la cassette</strong> pour comprendre où tout avait commencé.",
      syn: "revenir en arrière, refaire l’historique, reprendre depuis le début" },
    { mot: "aguerri", emoji: "🛡️", type: "adjectif",
      def: "Endurci par l’expérience, rendu plus résistant et compétent face aux difficultés.",
      ex: "Après cinq ans sur le terrain, l’équipe est bien plus <strong>aguerrie</strong>.",
      syn: "expérimenté, endurci, chevronné" },
    { mot: "de manière résolue", emoji: "💪", type: "expression",
      def: "Avec détermination, sans hésitation, en assumant pleinement une décision.",
      ex: "Elle a répondu <strong>de manière résolue</strong>, sans laisser place au doute.",
      syn: "avec détermination, fermement, résolument" },
    { mot: "rachitique", emoji: "🦴", type: "adjectif",
      def: "D’une maigreur ou d’une faiblesse extrême, au sens propre ou figuré (budget, croissance).",
      ex: "Le budget alloué au projet reste franchement <strong>rachitique</strong>.",
      syn: "chétif, squelettique, très insuffisant" },
    { mot: "parasiter", emoji: "🦟", type: "verbe",
      def: "Perturber ou gêner le fonctionnement normal de quelque chose en s’y greffant indûment.",
      ex: "Ces notifications incessantes finissent par <strong>parasiter</strong> toute concentration.",
      syn: "perturber, polluer, gêner" },
    { mot: "vierges effarouchées", emoji: "😳", type: "expression",
      def: "Se dit, souvent avec ironie, de personnes qui feignent une pudeur ou une innocence excessive.",
      ex: "Inutile de jouer les <strong>vierges effarouchées</strong>, tout le monde savait ce qui se préparait.",
      syn: "faire l’innocent, feindre la pudeur, jouer la surprise" },
    { mot: "bon an mal an", emoji: "📅", type: "expression",
      def: "En moyenne, d’une année sur l’autre, malgré les hauts et les bas.",
      ex: "<strong>Bon an mal an</strong>, l’entreprise dégage toujours une marge stable.",
      syn: "en moyenne, d’une année sur l’autre, tant bien que mal" },
    { mot: "conjuguer", emoji: "🔀", type: "verbe",
      def: "Combiner ou faire coexister deux éléments ou deux actions en même temps.",
      ex: "Il arrive à <strong>conjuguer</strong> vie de famille et déplacements professionnels incessants.",
      syn: "combiner, allier, concilier" },
    { mot: "me rouler dans la farine", emoji: "🌾", type: "expression",
      def: "Se faire tromper ou berner, souvent sans s’en rendre compte immédiatement.",
      ex: "Il s’est fait <strong>rouler dans la farine</strong> par un vendeur peu scrupuleux.",
      syn: "se faire duper, se faire avoir, se faire berner" },
    { mot: "cosmétique", emoji: "💄", type: "adjectif",
      def: "Qui ne change que l’apparence superficielle d’une chose, sans en modifier le fond.",
      ex: "Cette réforme reste largement <strong>cosmétique</strong>, les vrais problèmes ne sont pas traités.",
      syn: "superficiel, de façade, symbolique" },
    { mot: "se carapater", emoji: "🏃", type: "verbe",
      def: "S’enfuir discrètement et rapidement, souvent pour éviter une situation gênante.",
      ex: "Dès que la discussion s’est tendue, il s’est <strong>carapaté</strong> sans un mot.",
      syn: "filer, s’esquiver, déguerpir" },
    { mot: "clé de voûte", emoji: "🏛️", type: "expression",
      def: "Élément central sans lequel tout l’édifice ou le système s’effondrerait.",
      ex: "Cette clause est la <strong>clé de voûte</strong> de tout l’accord.",
      syn: "pilier central, élément essentiel, pierre angulaire" },
    { mot: "en filigrane", emoji: "🖼️", type: "expression",
      def: "Présent de façon discrète, sans être exprimé ouvertement, mais perceptible en arrière-plan.",
      ex: "On sent <strong>en filigrane</strong> une certaine inquiétude derrière son discours optimiste.",
      syn: "en arrière-plan, en sous-texte, de façon sous-entendue" },
    { mot: "peu ou prou", emoji: "🤏", type: "expression",
      def: "Plus ou moins, approximativement, sans grande précision.",
      ex: "Tout le monde a <strong>peu ou prou</strong> la même analyse de la situation.",
      syn: "à peu près, plus ou moins, grosso modo" },
    { mot: "nébuleux", emoji: "☁️", type: "adjectif",
      def: "Vague, confus, difficile à cerner précisément.",
      ex: "Son projet reste encore assez <strong>nébuleux</strong> à ce stade.",
      syn: "flou, confus, imprécis" },
    { mot: "faire son rabbi Jacob", emoji: "💃", type: "expression",
      def: "Expression familière et un peu datée, en référence au film culte de 1973, pour se réjouir ou célébrer de façon exubérante et théâtrale.",
      ex: "Dès l’annonce des résultats, il s’est mis à <strong>faire son rabbi Jacob</strong> devant tout le bureau.",
      syn: "exulter, célébrer avec exubérance, se réjouir bruyamment" },
    { mot: "loi de Brandolini", emoji: "⚖️", type: "expression",
      def: "Principe selon lequel l’énergie nécessaire pour réfuter une désinformation est très supérieure à celle qu’il a fallu pour la produire.",
      ex: "Face à cette rumeur, on retrouve la <strong>loi de Brandolini</strong> : dix minutes pour la lancer, des heures pour la démentir.",
      syn: "asymétrie de la désinformation, principe du bullshit, loi de l’âne" },
    { mot: "faire feu de tout bois", emoji: "🔥", type: "expression",
      def: "Utiliser tous les moyens disponibles, même les plus improbables, pour parvenir à un but.",
      ex: "En période de crise, l’équipe commerciale a fait <strong>feu de tout bois</strong> pour maintenir le chiffre d’affaires.",
      syn: "utiliser tous les moyens, ne rien négliger, tout tenter" },
    { mot: "se gargariser", emoji: "🥂", type: "verbe",
      def: "Se délecter avec une satisfaction excessive et un peu ridicule de quelque chose, souvent de ses propres propos.",
      ex: "Il <strong>se gargarise</strong> de ses succès passés plus qu’il ne prépare l’avenir.",
      syn: "se délecter, se pavaner, tirer une fierté excessive" },
    { mot: "le royaume de l’à peu près", emoji: "🌫️", type: "expression",
      def: "Univers où l’approximation règne, où rien n’est jamais précis ni rigoureux.",
      ex: "Sur ce chantier, on est en plein <strong>royaume de l’à peu près</strong>.",
      syn: "l’approximatif généralisé, le flou permanent, l’imprécision érigée en règle" },
    { mot: "omerta", emoji: "🤫", type: "nom",
      def: "Loi du silence, refus collectif et tacite de dénoncer ou de témoigner.",
      ex: "Une véritable <strong>omerta</strong> régnait sur les pratiques internes de l’entreprise.",
      syn: "loi du silence, silence collectif, pacte de silence" },
    { mot: "un tantinet", emoji: "🤏", type: "adverbe",
      def: "Un petit peu, légèrement, utilisé souvent avec une pointe d’ironie.",
      ex: "Son discours était un <strong>tantinet</strong> exagéré, pour ne pas dire plus.",
      syn: "un peu, légèrement, quelque peu" },
    { mot: "le mariage de la carpe et du lapin", emoji: "🐟", type: "expression",
      def: "Association de deux éléments totalement incompatibles, vouée à mal fonctionner.",
      ex: "Fusionner ces deux équipes aux cultures opposées, c’est le <strong>mariage de la carpe et du lapin</strong>.",
      syn: "association contre-nature, mélange incompatible, alliance improbable" },
    { mot: "être en ordre de marche", emoji: "🚶", type: "expression",
      def: "Être prêt et organisé pour agir immédiatement, tous les éléments étant en place.",
      ex: "L’équipe est désormais <strong>en ordre de marche</strong> pour le lancement.",
      syn: "être prêt, être opérationnel, être fin prêt" },
    { mot: "c’est la politique de l’autruche", emoji: "🦩", type: "expression",
      def: "Refuser de voir un problème évident en préférant l’ignorer plutôt que d’y faire face.",
      ex: "Ignorer les signaux d’alerte, c’est la <strong>politique de l’autruche</strong>.",
      syn: "faire l’autruche, se voiler la face, refuser de voir la réalité" },
    { mot: "biais de confirmation", emoji: "🧠", type: "nom",
      def: "Tendance à privilégier les informations qui confirment ses croyances existantes, en ignorant celles qui les contredisent.",
      ex: "Il ne lit que des articles qui vont dans son sens, un vrai <strong>biais de confirmation</strong>.",
      syn: "biais cognitif, filtre de confirmation, aveuglement sélectif" },
    { mot: "biais de disponibilité", emoji: "🧠", type: "nom",
      def: "Tendance à surestimer la fréquence d’un événement parce qu’il vient facilement à l’esprit, souvent à cause de sa forte médiatisation.",
      ex: "Après ce reportage, tout le monde surestime le risque par <strong>biais de disponibilité</strong>.",
      syn: "biais cognitif, surestimation par familiarité, heuristique de disponibilité" },
    { mot: "biais de nostalgie", emoji: "🧠", type: "nom",
      def: "Tendance à idéaliser le passé en occultant ses aspects négatifs, au profit d’une vision embellie.",
      ex: "Il se souvient de son ancien travail avec un <strong>biais de nostalgie</strong> évident.",
      syn: "idéalisation du passé, nostalgie sélective, vision embellie du passé" },
    { mot: "avoir une empreinte sur", emoji: "👣", type: "expression",
      def: "Exercer une influence marquante et durable sur quelque chose ou quelqu’un.",
      ex: "Ce mentor a eu une réelle <strong>empreinte sur</strong> sa manière de manager.",
      syn: "influencer durablement, marquer, laisser sa trace sur" },
    { mot: "effet Dunning-Kruger", emoji: "🎓", type: "nom",
      def: "Biais cognitif par lequel les moins compétents surestiment leurs compétences, faute de savoir ce qu’ils ignorent.",
      ex: "Son assurance sur un sujet qu’il maîtrise à peine sent bon l’<strong>effet Dunning-Kruger</strong>.",
      syn: "surconfiance des débutants, biais de surestimation, incompétence inconsciente" },
    { mot: "être le juge de paix", emoji: "⚖️", type: "expression",
      def: "Être l’élément décisif qui permet de trancher définitivement un débat ou une situation.",
      ex: "Le vote des indécis sera le <strong>juge de paix</strong> de cette élection.",
      syn: "facteur décisif, élément tranchant, arbitre final" },
    { mot: "miroir aux alouettes", emoji: "🪞", type: "expression",
      def: "Piège séduisant en apparence, qui attire par une promesse illusoire.",
      ex: "Cette offre trop belle pour être vraie est un vrai <strong>miroir aux alouettes</strong>.",
      syn: "leurre, piège séduisant, illusion trompeuse" },
    { mot: "goupiller", emoji: "🔧", type: "verbe",
      def: "Arranger ou organiser une affaire, parfois avec un peu de débrouille ou de manière habile.",
      ex: "Il a réussi à <strong>goupiller</strong> un arrangement satisfaisant pour tout le monde.",
      syn: "arranger, manigancer, combiner" },
    { mot: "sophisme de l’homme de paille", emoji: "🥸", type: "nom",
      def: "Argument fallacieux qui consiste à déformer la position de l’adversaire pour la réfuter plus facilement.",
      ex: "Répondre à un argument qu’il n’a jamais tenu, c’est un pur <strong>sophisme de l’homme de paille</strong>.",
      syn: "straw man, argument déformé, épouvantail rhétorique" },
    { mot: "sophisme de la division / décomposition", emoji: "🧩", type: "nom",
      def: "Erreur de raisonnement qui attribue à chaque partie d’un tout une propriété qui n’appartient qu’à l’ensemble.",
      ex: "Dire que chaque joueur est mauvais parce que l’équipe a perdu, c’est un <strong>sophisme de la division</strong>.",
      syn: "erreur de raisonnement, faux syllogisme, sophisme logique" },
    { mot: "syndrome du personnage principal", emoji: "🎬", type: "nom",
      def: "Tendance à se percevoir comme le héros central de toute situation, au détriment de la perspective des autres.",
      ex: "Il a un vrai <strong>syndrome du personnage principal</strong>, tout tourne toujours autour de lui.",
      syn: "égocentrisme narratif, complexe du héros, se croire au centre du monde" },
    { mot: "centre névralgique", emoji: "🧠", type: "expression",
      def: "Point stratégique et vital autour duquel tout un système s’organise.",
      ex: "Cette salle de contrôle est le <strong>centre névralgique</strong> de toute l’usine.",
      syn: "cœur du système, point stratégique, noyau vital" },
    { mot: "cas de force majeure", emoji: "🌪️", type: "expression",
      def: "Événement imprévisible et incontrôlable qui exonère de responsabilité en cas de manquement.",
      ex: "L’annulation a été justifiée par un <strong>cas de force majeure</strong>.",
      syn: "événement imprévisible, circonstance exceptionnelle, cas fortuit" },
    { mot: "kafkaïen", emoji: "🌀", type: "adjectif",
      def: "Absurde et oppressant, à la manière des situations administratives inextricables décrites par Kafka.",
      ex: "Renouveler ce document a viré au parcours <strong>kafkaïen</strong>.",
      syn: "absurde, labyrinthique, ubuesque" },
    { mot: "pantagruélique", emoji: "🍗", type: "adjectif",
      def: "D’une abondance démesurée, en référence à l’appétit du géant Pantagruel de Rabelais (souvent pour un repas).",
      ex: "Ils ont enchaîné un repas <strong>pantagruélique</strong> qui a duré tout l’après-midi.",
      syn: "gargantuesque, plantureux, copieux à l’excès" },
    { mot: "séculaire", emoji: "🏰", type: "adjectif",
      def: "Qui existe depuis un siècle ou plus, profondément ancré dans le temps long.",
      ex: "Cette rivalité <strong>séculaire</strong> entre les deux villages remonte à plusieurs générations.",
      syn: "centenaire, ancestral, très ancien" },
    { mot: "pléthorique", emoji: "📦", type: "adjectif",
      def: "Présent en très grande quantité, au point de devenir excessif.",
      ex: "L’offre de formations en ligne est aujourd’hui <strong>pléthorique</strong>.",
      syn: "surabondant, excessif, foisonnant" },
    { mot: "au compte-goutte", emoji: "💧", type: "expression",
      def: "Distribué ou révélé très progressivement, en quantités minimes à la fois.",
      ex: "Les informations n’arrivent qu’<strong>au compte-goutte</strong>, ce qui alimente les rumeurs.",
      syn: "parcimonieusement, très progressivement, avec parcimonie" },
    { mot: "défrayer la chronique", emoji: "📰", type: "expression",
      def: "Faire beaucoup parler de soi, souvent de façon scandaleuse ou spectaculaire, dans l’actualité.",
      ex: "Cette affaire a <strong>défrayé la chronique</strong> pendant plusieurs semaines.",
      syn: "faire la une, alimenter les conversations, faire scandale" },
    { mot: "il vaut mieux se couper un doigt que se couper un bras", emoji: "✋", type: "expression",
      def: "Mieux vaut accepter une petite perte immédiate plutôt que risquer d’en subir une bien plus grande plus tard.",
      ex: "Renoncer maintenant à ce petit contrat : <strong>il vaut mieux se couper un doigt que se couper un bras</strong>.",
      syn: "mieux vaut un petit sacrifice qu’un grand, couper ses pertes tôt, sacrifice mineur préventif" },
    { mot: "pile je gagne, face tu perds", emoji: "🪙", type: "expression",
      def: "Se dit d’une situation truquée où l’un des partis gagne systématiquement, quel que soit le résultat.",
      ex: "Dans cette négociation, c’est toujours <strong>pile je gagne, face tu perds</strong> pour eux.",
      syn: "jeu truqué, situation biaisée, arrangement à sens unique" },
    { mot: "se mettre en jachère", emoji: "🌾", type: "expression",
      def: "Marquer une pause volontaire et prolongée, comme une terre laissée au repos pour se régénérer.",
      ex: "Après ce projet épuisant, il a décidé de <strong>se mettre en jachère</strong> quelques mois.",
      syn: "faire une pause prolongée, se mettre au repos, lever le pied durablement" },
    { mot: "chape de plomb", emoji: "⚫", type: "expression",
      def: "Silence pesant et contraignant qui empêche toute expression ou circulation d’information.",
      ex: "Une <strong>chape de plomb</strong> est retombée sur l’affaire après l’intervention de la direction.",
      syn: "silence pesant, chape de silence, étouffement de l’information" },
    { mot: "être empreint de", emoji: "🖋️", type: "expression",
      def: "Être marqué, imprégné d’un sentiment ou d’une qualité particulière.",
      ex: "Son discours était <strong>empreint</strong> d’une grande sincérité.",
      syn: "imprégné de, teinté de, marqué par" },
    { mot: "faisceau d’indices", emoji: "🔦", type: "nom",
      def: "Ensemble d’éléments convergents qui, mis bout à bout, orientent vers une même conclusion.",
      ex: "Le <strong>faisceau d’indices</strong> pointait clairement vers la même explication.",
      syn: "ensemble convergent, concordance d’éléments, convergence de preuves" },
    { mot: "exogène / endogène", emoji: "🔄", type: "adjectif",
      def: "Qui provient de l’extérieur (exogène) ou qui provient de l’intérieur d’un système (endogène).",
      ex: "Cette crise est d’origine <strong>exogène</strong>, contrairement à la précédente qui était <strong>endogène</strong>.",
      syn: "externe / interne, d’origine extérieure / d’origine intérieure" },
    { mot: "in vivo / in vitro", emoji: "🧪", type: "expression",
      def: "Réalisé sur un organisme vivant réel (in vivo) plutôt qu’en laboratoire dans un environnement artificiel (in vitro).",
      ex: "Les résultats <strong>in vivo</strong> ne confirment pas toujours ce qu’on observe <strong>in vitro</strong>.",
      syn: "sur le vivant / en laboratoire, en conditions réelles / en conditions artificielles" },
    { mot: "avec ceinture et bretelles", emoji: "🎽", type: "expression",
      def: "En multipliant les précautions et sécurités, parfois de façon redondante.",
      ex: "Ils ont sécurisé le déploiement <strong>avec ceinture et bretelles</strong>, deux systèmes de sauvegarde en parallèle.",
      syn: "par excès de précaution, en double sécurité, redondance de précautions" },
    { mot: "ouvrir la boîte de Pandore", emoji: "📦", type: "expression",
      def: "Déclencher une série de conséquences incontrôlables en abordant un sujet ou une action qu’on ne peut plus arrêter.",
      ex: "Relancer ce débat, c’est <strong>ouvrir la boîte de Pandore</strong>.",
      syn: "déclencher l’irréversible, ouvrir une brèche incontrôlable, libérer des maux" },
    { mot: "congruence", emoji: "🔺", type: "nom",
      def: "Fait de coïncider parfaitement, d’être en accord ou en cohérence totale avec autre chose.",
      ex: "Il y a une réelle <strong>congruence</strong> entre son discours et ses actes.",
      syn: "cohérence, concordance, correspondance" },
    { mot: "abhorrer", emoji: "🤢", type: "verbe",
      def: "Détester profondément, éprouver une aversion extrême pour quelque chose.",
      ex: "Elle <strong>abhorre</strong> le mensonge sous toutes ses formes.",
      syn: "détester, exécrer, avoir horreur de" },
    { mot: "procès d’intention", emoji: "⚖️", type: "expression",
      def: "Reproche fait à quelqu’un sur ses intentions supposées, plutôt que sur ses actes réels.",
      ex: "Arrête de lui faire un <strong>procès d’intention</strong>, il n’a encore rien fait de mal.",
      syn: "préjugé sur les intentions, accusation anticipée, jugement a priori" },
    { mot: "pour des raisons structurelles… et pour des raisons conjoncturelles…", emoji: "📊", type: "expression",
      def: "Causes profondes et durables (structurelles) opposées aux causes temporaires liées au contexte du moment (conjoncturelles).",
      ex: "La baisse s’explique en partie <strong>pour des raisons structurelles</strong>, et en partie <strong>pour des raisons conjoncturelles</strong>.",
      syn: "causes de fond / causes ponctuelles, permanent / temporaire" },
    { mot: "essentialiser", emoji: "🧬", type: "verbe",
      def: "Réduire une personne ou un groupe à une essence figée, en ignorant sa complexité et sa diversité réelle.",
      ex: "<strong>Essentialiser</strong> tout un groupe à partir du comportement de quelques-uns est toujours réducteur.",
      syn: "réduire à une essence, figer dans une catégorie, généraliser abusivement" },
    { mot: "réduire la voilure", emoji: "⛵", type: "expression",
      def: "Diminuer volontairement l’ampleur ou l’ambition d’un projet, souvent pour s’adapter à des moyens réduits.",
      ex: "Faute de budget, l’équipe a dû <strong>réduire la voilure</strong> sur ce projet.",
      syn: "revoir à la baisse, freiner l’ambition, lever le pied" },
    { mot: "croisement des intérêts", emoji: "🔀", type: "expression",
      def: "Situation où plusieurs intérêts, parfois divergents, se rencontrent et interagissent sur un même sujet.",
      ex: "Ce dossier illustre bien le <strong>croisement des intérêts</strong> entre les différentes parties prenantes.",
      syn: "rencontre d’intérêts, intersection d’enjeux, convergence d’intérêts" },
    { mot: "myriade", emoji: "✨", type: "nom",
      def: "Très grand nombre, quantité immense difficile à dénombrer précisément.",
      ex: "Une <strong>myriade</strong> de petites étoiles scintillait dans le ciel.",
      syn: "multitude, foule innombrable, profusion" },
    { mot: "point Godwin", emoji: "🌀", type: "expression",
      def: "Moment où, dans un débat, l’un des participants compare son adversaire à Hitler ou aux nazis, souvent signe d’un argument à bout de souffle.",
      ex: "Dès que la comparaison nazie est arrivée, on a atteint le <strong>point Godwin</strong> de la discussion.",
      syn: "loi de Godwin, comparaison outrancière, argument disqualifiant" },
    { mot: "syndrome de Stockholm", emoji: "🎗️", type: "expression",
      def: "Phénomène psychologique par lequel une victime développe une empathie, voire une affection, envers son agresseur.",
      ex: "Il a fini par défendre son ancien employeur toxique, un vrai <strong>syndrome de Stockholm</strong> professionnel.",
      syn: "attachement paradoxal à l’agresseur, identification à l’oppresseur" },
    { mot: "galvaudé", emoji: "🪙", type: "adjectif",
      def: "Employé à tort et à travers, au point d’avoir perdu son sens précis ou sa force initiale.",
      ex: "Le mot <em>révolutionnaire</em> est tellement <strong>galvaudé</strong> qu’il ne veut presque plus rien dire.",
      syn: "dévalué par l’usage, banalisé, vidé de son sens" },
    { mot: "subrepticement", emoji: "🥷", type: "adverbe",
      def: "De façon discrète et furtive, sans se faire remarquer, presque en cachette.",
      ex: "Il a quitté la réunion <strong>subrepticement</strong>, sans que personne ne s’en aperçoive.",
      syn: "furtivement, discrètement, en catimini" },
    { mot: "enfoncer des portes ouvertes", emoji: "🚪", type: "expression",
      def: "Démontrer avec effort quelque chose qui est déjà évident pour tout le monde.",
      ex: "Rappeler qu’il faut dormir pour être en forme, c’est <strong>enfoncer des portes ouvertes</strong>.",
      syn: "dire une évidence, prêcher un converti, enfoncer l’évidence" },
    { mot: "tu m’as coupé l’herbe sous le pied", emoji: "✂️", type: "expression",
      def: "Devancer quelqu’un dans une action ou une idée, en lui retirant l’occasion d’agir en premier.",
      ex: "Il m’a <strong>coupé l’herbe sous le pied</strong> en proposant l’idée juste avant moi.",
      syn: "devancer, griller la politesse, prendre de vitesse" },
    { mot: "faire un impair", emoji: "🙊", type: "expression",
      def: "Commettre une maladresse sociale ou une erreur de tact, souvent involontaire.",
      ex: "Il a fait un <strong>impair</strong> en évoquant ce sujet sensible devant tout le monde.",
      syn: "gaffe, maladresse, faux pas" },
    { mot: "vaste fumisterie", emoji: "🎪", type: "nom",
      def: "Chose qui se prétend sérieuse ou fondée mais qui n’est en réalité qu’une tromperie ou une escroquerie sans valeur.",
      ex: "Ce prétendu remède miracle est une <strong>vaste fumisterie</strong>.",
      syn: "escroquerie, tromperie, arnaque" },
    { mot: "c’est un serpent de mer", emoji: "🐍", type: "expression",
      def: "Sujet qui revient régulièrement dans l’actualité sans jamais vraiment se résoudre.",
      ex: "La réforme des retraites est un vrai <strong>serpent de mer</strong> politique.",
      syn: "marronnier récurrent, sujet qui traîne, dossier sans fin" },
    { mot: "ça fait psychologie de comptoir", emoji: "🍺", type: "expression",
      def: "Analyse simpliste et peu fondée, digne d’une conversation de bistrot plutôt que d’une expertise réelle.",
      ex: "Expliquer son échec par son signe astrologique, ça fait <strong>psychologie de comptoir</strong>.",
      syn: "analyse simpliste, pseudo-expertise, raisonnement de bistrot" },
    { mot: "complétude", emoji: "🧩", type: "nom",
      def: "Caractère de ce qui est complet, qui ne manque d’aucun élément nécessaire.",
      ex: "Le rapport a été validé après vérification de sa <strong>complétude</strong>.",
      syn: "exhaustivité, intégralité, caractère complet" },
    { mot: "j’en fais à la marge", emoji: "🤏", type: "expression",
      def: "Faire quelque chose de façon limitée, en quantité réduite, sans que ce soit central dans l’activité.",
      ex: "Je continue à en faire <strong>à la marge</strong>, mais ce n’est plus mon activité principale.",
      syn: "marginalement, un peu, de façon limitée" },
    { mot: "faire du neuf avec du vieux", emoji: "♻️", type: "expression",
      def: "Créer quelque chose de nouveau ou d’utile à partir d’éléments anciens ou déjà existants.",
      ex: "Ce designer excelle à <strong>faire du neuf avec du vieux</strong> en recyclant les meubles.",
      syn: "recycler, réinventer l’existant, transformer l’ancien" },
    { mot: "se mettre au diapason", emoji: "🎵", type: "expression",
      def: "S’accorder, s’ajuster au ton, au rythme ou à l’état d’esprit du groupe ou de la situation.",
      ex: "Il a fallu <strong>se mettre au diapason</strong> rapidement pour suivre le rythme de l’équipe.",
      syn: "s’harmoniser, s’accorder, s’ajuster" },
    { mot: "mélange des genres", emoji: "🎭", type: "expression",
      def: "Confusion entre deux domaines ou registres qui devraient normalement rester distincts.",
      ex: "Mêler vie privée et décisions professionnelles, c’est un <strong>mélange des genres</strong> risqué.",
      syn: "confusion des rôles, amalgame, brouillage des frontières" },
    { mot: "secret de polichinelle", emoji: "🤐", type: "expression",
      def: "Chose censée être secrète mais que tout le monde connaît déjà en réalité.",
      ex: "Leur rupture était un <strong>secret de polichinelle</strong> depuis des mois.",
      syn: "secret que tout le monde connaît, fausse confidence, évidence dissimulée" },
    { mot: "mettre le bleu de chauffe", emoji: "👷", type: "expression",
      def: "Se préparer concrètement à un travail exigeant, en tenue adaptée pour l’effort à venir.",
      ex: "Il va falloir <strong>mettre le bleu de chauffe</strong> pour tenir les délais.",
      syn: "se retrousser les manches, se préparer à l’effort, s’atteler à la tâche" },
    { mot: "savoir ménager la chèvre et le chou", emoji: "🐐", type: "expression",
      def: "Réussir à satisfaire deux parties aux intérêts opposés sans froisser ni l’une ni l’autre.",
      ex: "Le médiateur a su <strong>ménager la chèvre et le chou</strong> dans cette négociation tendue.",
      syn: "contenter tout le monde, jouer les équilibristes, concilier des intérêts opposés" },
    { mot: "la substantifique moelle", emoji: "🦴", type: "expression",
      def: "L’essence la plus riche et la plus précieuse d’une chose, ce qu’il faut en retenir au fond.",
      ex: "Il a su tirer la <strong>substantifique moelle</strong> de ce long rapport en trois phrases.",
      syn: "l’essentiel, la quintessence, le cœur du sujet" },
    { mot: "changement de paradigme", emoji: "🔄", type: "expression",
      def: "Bouleversement complet de la façon dont on pense ou aborde un domaine, remplaçant l’ancien modèle de référence.",
      ex: "L’intelligence artificielle a provoqué un véritable <strong>changement de paradigme</strong> dans de nombreux métiers.",
      syn: "révolution conceptuelle, rupture de modèle, bascule de référence" },
    { mot: "avoir une main de fer dans un gant de velours", emoji: "🧤", type: "expression",
      def: "Exercer une autorité ferme tout en la dissimulant sous des dehors doux et courtois.",
      ex: "Cette directrice a une <strong>main de fer dans un gant de velours</strong> : toujours souriante, jamais complaisante.",
      syn: "fermeté sous des dehors doux, autorité discrète, poigne dissimulée" },
    { mot: "les arbres aux racines profondes sont ceux qui montent le plus haut", emoji: "🌳", type: "expression",
      def: "Une base solide et bien ancrée est la condition pour atteindre de grandes réussites durables.",
      ex: "On lui rappelle souvent que les <strong>arbres aux racines profondes sont ceux qui montent le plus haut</strong>, pour valoriser la patience.",
      syn: "les bases solides mènent loin, patience et fondations, la solidité avant la hauteur" },
    { mot: "un tiens vaut mieux que deux tu l’auras", emoji: "🐦", type: "expression",
      def: "Proverbe classique : il vaut mieux se contenter d’un avantage certain plutôt que de risquer de tout perdre pour un gain hypothétique plus grand.",
      ex: "Il a accepté l’offre immédiatement, fidèle au principe qu’<strong>un tiens vaut mieux que deux tu l’auras</strong>.",
      syn: "mieux vaut peu que rien, la certitude plutôt que l’espoir, prudence plutôt qu’avidité" },
    { mot: "voyager, c’est la seule chose qu’on achète et qui te rend plus riche", emoji: "✈️", type: "expression",
      def: "Contrairement aux biens matériels, les expériences de voyage enrichissent durablement sans jamais s’user.",
      ex: "Elle cite souvent l’idée que <strong>voyager, c’est la seule chose qu’on achète et qui te rend plus riche</strong> pour justifier ses économies.",
      syn: "la richesse de l’expérience, l’investissement en soi, l’enrichissement immatériel" },
    { mot: "les vainqueurs écrivent l’Histoire, les vaincus la racontent", emoji: "📖", type: "expression",
      def: "Variante d’un adage classique : les gagnants figent le récit officiel, mais ce sont souvent les perdants qui transmettent oralement leur propre version.",
      ex: "Il aime rappeler que <strong>les vainqueurs écrivent l’Histoire, les vaincus la racontent</strong>, pour nuancer tout récit officiel.",
      syn: "histoire officielle contre mémoire orale, versions concurrentes du passé" },
    { mot: "la plupart des gens préfèrent être dans la majorité que d’avoir raison", emoji: "👥", type: "expression",
      def: "Souligne combien le confort de l’appartenance au groupe pèse souvent plus lourd que la conviction personnelle d’avoir raison seul.",
      ex: "Sur ce sujet clivant, <strong>la plupart des gens préfèrent être dans la majorité que d’avoir raison</strong>, ce qui explique le silence général.",
      syn: "le conformisme avant la conviction, la sécurité du nombre, suivre le troupeau" },
    { mot: "ce n’est pas 12 hommes en colère, tout le monde n’était pas d’accord à la fin", emoji: "🎬", type: "expression",
      def: "Référence au film où un jury finit par un consensus unanime — utilisé pour souligner que la réalité se termine rarement par un accord général.",
      ex: "Après le vote, il a lâché que <strong>ce n’est pas 12 hommes en colère</strong>, tout le monde n’était clairement pas d’accord à la fin.",
      syn: "absence de consensus réel, désaccord persistant, fin ouverte" },
    { mot: "le maître a échoué plus de fois que l’apprenti n’a essayé", emoji: "🎓", type: "expression",
      def: "L’expertise se construit par une accumulation d’échecs bien plus grande que le nombre total de tentatives d’un débutant.",
      ex: "Elle se console de ses erreurs en se rappelant que <strong>le maître a échoué plus de fois que l’apprenti n’a essayé</strong>.",
      syn: "l’expérience se paie par l’échec répété, la maîtrise née de la persévérance" }
  ];

  var TYPE_LABELS = {
    verbe: "Verbe", adjectif: "Adjectif", nom: "Nom", adverbe: "Adverbe",
    expression: "Expression", anecdote: "Anecdote culturelle"
  };
  var GROUP_LABELS = { tous: "Tous", mots: "Mots", expressions: "Expressions", anecdote: "Anecdote" };
  var GROUP_OF = { verbe: "mots", adjectif: "mots", nom: "mots", adverbe: "mots", expression: "expressions", anecdote: "anecdote" };

  BASE_ENTRIES.forEach(function (e, i) { e.id = i; e.group = GROUP_OF[e.type]; });
