// Données du Carnet IT (Infra, Cloud, Sécurité & IA) — chargé comme <script src>
// classique (pas de module), donc ces var deviennent globales. Fichier indépendant
// de words-data.js (le carnet de vocabulaire), pour ne rien mélanger.

  var BASE_ENTRIES = [
    { mot: "DevOps", emoji: "🤝", type: "devops",
      def: "Culture / approche organisationnelle qui vise à rapprocher les équipes de développement (Dev) et d’exploitation (Ops) pour livrer plus vite, plus souvent et plus fiablement. Le CI/CD et l’IaC sont les pratiques techniques qui concrétisent cette culture — ce ne sont pas des synonymes.",
      ex: "Une équipe DevOps ne se contente pas d’écrire du code : elle est aussi responsable de le déployer et de le faire tourner en production, au lieu de « lancer par-dessus le mur » à une équipe Ops séparée.",
      syn: "culture, pas un outil", date: "2026-09-24" },
    { mot: "CI/CD", emoji: "🔁", type: "devops",
      def: "Intégration et déploiement continus : la pratique qui permet de livrer du code vite et souvent. C’est le cœur opérationnel du DevOps.",
      ex: "Dès qu’un développeur pousse son code, une chaîne CI/CD lance automatiquement les tests, construit l’application et la déploie, sans intervention manuelle.",
      syn: "cœur opérationnel du DevOps", date: "2026-09-24" },
    { mot: "IaC (Infrastructure as Code)", emoji: "📜", type: "devops",
      def: "Applique la logique DevOps à l’infrastructure elle-même : décrire des serveurs, réseaux et firewalls dans des fichiers versionnés plutôt que de les configurer à la main, pour automatiser et reproduire leur création.",
      ex: "Au lieu de cliquer manuellement pour créer 12 VMs, on écrit un fichier qui les décrit ; le relancer les recrée à l’identique en 20 minutes, sur n’importe quel environnement.",
      syn: "automatisation, versioning, reproductibilité", date: "2026-09-24" },
    { mot: "Pipeline vs Workflow", emoji: "🧵", type: "devops",
      def: "Workflow = terme général : n’importe quelle suite d’étapes pour accomplir une tâche (humaine ou automatisée). Pipeline = un type de workflow technique et automatisé, où les étapes s’enchaînent en série, chacune passant son résultat à la suivante. Tout pipeline est un workflow, mais tout workflow n’est pas un pipeline.",
      ex: "« Workflow de validation d’une facture » (des humains qui se relaient) est un workflow mais pas un pipeline ; « compilation → tests → déploiement » enchaîné automatiquement est un pipeline.",
      syn: "", date: "2026-09-24" },
    { mot: "OpenTofu (Terraform OSS)", emoji: "🏗️", type: "devops",
      def: "Outil d’IaC qui crée l’infrastructure physique/virtuelle : VMs, réseaux, firewalls, stockage — la première couche, celle qui prépare « le terrain ».",
      ex: "Pour un nouvel hôpital, OpenTofu crée 12 VMs en 20 minutes sur OVHcloud, avec réseaux et firewalls déjà configurés.",
      syn: "IaC, le terrain", date: "2026-09-24" },
    { mot: "Ansible", emoji: "🛠️", type: "devops",
      def: "Outil qui configure les serveurs une fois créés : installation des dépendances, réglages de l’OS, application des règles de sécurité.",
      ex: "Une fois qu’OpenTofu a créé les 12 VMs, Ansible installe les dépendances et applique les règles de sécurité — les serveurs sont prêts à l’emploi.",
      syn: "IaC, configuration post-création", date: "2026-09-24" },
    { mot: "GitLab CI", emoji: "✅", type: "devops",
      def: "Outil de CI : dès qu’un développeur soumet du code, il lance automatiquement les tests, le contrôle de sécurité et la construction de l’image applicative.",
      ex: "Un développeur corrige un bug ; GitLab CI lance aussitôt 300 tests automatiques et construit l’image de l’application.",
      syn: "CI, le code", date: "2026-09-24" },
    { mot: "Harbor", emoji: "📦", type: "devops",
      def: "Registre qui stocke les images applicatives validées par la CI — l’entrepôt des versions prêtes à être déployées.",
      ex: "Une fois les 300 tests passés, GitLab CI dépose l’image validée dans Harbor, en attendant son déploiement.",
      syn: "CI/CD, entrepôt d’images", date: "2026-09-24" },
    { mot: "Helm", emoji: "🪄", type: "devops",
      def: "Empaquette une application Kubernetes (qui nécessite normalement des dizaines de fichiers YAML) en un seul « chart » installable en une commande.",
      ex: "Déployer une application sur Kubernetes sans Helm, c’est monter un meuble IKEA de 47 pièces avec 12 notices différentes. Helm, c’est le même meuble livré pré-assemblé avec une seule notice d’une page.",
      syn: "équivalent conceptuel : APT/RPM sous Linux, npm pour JavaScript", date: "2026-09-24" },
    { mot: "ArgoCD", emoji: "🚀", type: "devops",
      def: "Détecte les nouvelles versions d’images et les déploie automatiquement via Helm sur Kubernetes ; il surveille aussi en permanence que la configuration réellement en production correspond à celle écrite dans Git, et peut corriger tout écart.",
      ex: "Un admin modifie Keycloak à la main en pleine nuit pour corriger un bug urgent : la prod ne correspond plus à Git. ArgoCD détecte l’écart, alerte l’équipe et peut remettre la configuration conforme automatiquement.",
      syn: "contrôle de conformité, pas de la supervision de santé", date: "2026-09-24" },
    { mot: "Canary Release", emoji: "🐤", type: "devops",
      def: "Technique de déploiement où l’on pousse une nouvelle version à un petit pourcentage d’utilisateurs d’abord ; si tout va bien, on élargit progressivement jusqu’à 100 %.",
      ex: "Référence aux canaris que les mineurs descendaient en cage dans les mines de charbon : plus sensibles aux gaz toxiques, s’ils mouraient il fallait évacuer immédiatement. Le canary release joue le même rôle de détecteur précoce pour un déploiement logiciel.",
      syn: "déploiement canari", date: "2026-09-24" },
    { mot: "Blueprint", emoji: "📐", type: "devops",
      def: "Pas un logiciel, mais un plan d’architecture pré-conçu qui intègre nativement des exigences (sécurité, réglementaires) plutôt que de les rajouter après coup.",
      ex: "L’équivalent d’un plan de maison aux normes anti-sismiques déjà intégrées, plutôt que de construire la maison puis la renforcer ensuite.",
      syn: "", date: "2026-09-24" },
    { mot: "VM vs Conteneur", emoji: "📦", type: "virtu",
      def: "Deux façons d’isoler une application, à des niveaux différents. VM : isolation physique, chaque VM embarque son propre OS complet (lourd, plusieurs minutes pour démarrer). Conteneur : isolation logique, les conteneurs partagent le noyau de l’OS hôte (léger, démarre en quelques secondes).",
      ex: "Isolation forte requise ou OS différents sur une même machine → VM (VMware, XCP-NG, Proxmox). Applications modernes, microservices, scalabilité rapide → conteneur (Docker, containerd).",
      syn: "un hyperviseur héberge des VMs ; à l’intérieur, Kubernetes orchestre des conteneurs — deux niveaux superposés, pas concurrents", date: "2026-09-24" },
    { mot: "Kubernetes (K8s)", emoji: "🎼", type: "virtu",
      def: "Orchestrateur de conteneurs : il gère le déploiement, la mise à l’échelle et la disponibilité de dizaines ou centaines de conteneurs répartis sur un cluster de serveurs.",
      ex: "Le chef d’orchestre d’un ensemble de centaines de musiciens (les conteneurs). Si un musicien tombe malade (un conteneur plante), Kubernetes en relance automatiquement un autre ; si la salle est pleine, il ajoute des musiciens (scaling automatique).",
      syn: "auto-healing, auto-scaling, rolling updates, load balancing", date: "2026-09-24" },
    { mot: "Auto-healing", emoji: "🩹", type: "virtu",
      def: "Fonction de Kubernetes qui redémarre automatiquement un conteneur défaillant, sans intervention humaine.",
      ex: "Un conteneur applicatif plante à 3h du matin : Kubernetes en relance un nouveau instantanément, personne n’est réveillé.",
      syn: "", date: "2026-09-24" },
    { mot: "Auto-scaling", emoji: "📈", type: "virtu",
      def: "Fonction de Kubernetes qui ajoute ou retire automatiquement des instances d’une application selon la charge réelle.",
      ex: "Un pic de trafic double la charge du site : Kubernetes ajoute automatiquement des conteneurs supplémentaires, puis les retire une fois le pic passé.",
      syn: "", date: "2026-09-24" },
    { mot: "Rolling updates", emoji: "🔄", type: "virtu",
      def: "Fonction de Kubernetes qui met à jour une application progressivement, sans interruption de service pour les utilisateurs.",
      ex: "Une nouvelle version est déployée conteneur par conteneur pendant que les autres continuent de servir les utilisateurs — personne ne voit de coupure.",
      syn: "", date: "2026-09-24" },
    { mot: "Stockage bloc vs stockage objet", emoji: "🗄️", type: "virtu",
      def: "Stockage bloc (comme un disque dur classique) : accès par un seul serveur à la fois, très rapide, taillé pour les bases de données. Stockage objet (Ceph, comme Amazon S3) : accès par tous les serveurs simultanément, plus lent mais massivement scalable, taillé pour les fichiers.",
      ex: "La base PostgreSQL de Keycloak écrit sur du stockage bloc (performances maximales, accès exclusif). Les documents Nextcloud uploadés par 800 hôpitaux sont stockés dans Ceph : chaque fichier a une URL unique, accessible par des milliers d’utilisateurs en même temps.",
      syn: "", date: "2026-09-24" },
    { mot: "Firewall réseau", emoji: "🧱", type: "securite",
      def: "Filtre ce qui entre ou sort selon l’IP, le port et le protocole — il ne regarde pas le contenu des échanges.",
      ex: "Un scan de ports suspect est bloqué directement par le firewall, avant même d’atteindre l’application.",
      syn: "Stormshield (certifié ANSSI) ; Palo Alto, Fortinet, Cisco", date: "2026-09-24" },
    { mot: "WAF", emoji: "🛡️", type: "securite",
      def: "Web Application Firewall : inspecte le contenu des requêtes web (injections SQL, XSS…) devant chaque application, contrairement au firewall réseau qui ne regarde que l’adresse/le port.",
      ex: "Un attaquant passe par le site public en HTTPS légitime mais injecte du code dans un formulaire : le WAF reconnaît l’injection SQL et la bloque.",
      syn: "Ubika (ex-DenyAll, qualifié ANSSI) ; Imperva, F5, Cloudflare WAF", date: "2026-09-24" },
    { mot: "EPP/EDR", emoji: "🦠", type: "securite",
      def: "EPP = antivirus nouvelle génération, préventif. EDR = surveillance comportementale + isolation automatique, réactif : il détecte un comportement anormal après coup et agit.",
      ex: "Un attaquant exploite une faille non patchée et exécute du code malveillant : l’EDR détecte le comportement anormal, isole automatiquement le serveur compromis et alerte.",
      syn: "HarfangLab (certifié ANSSI) ; CrowdStrike, SentinelOne, MS Defender", date: "2026-09-24" },
    { mot: "Scan de vulnérabilités", emoji: "🔍", type: "securite",
      def: "Compare les versions logicielles installées aux failles (CVE) déjà connues, pour anticiper les problèmes avant qu’ils ne soient exploités.",
      ex: "L’outil avait signalé une faille non patchée des semaines avant qu’un attaquant ne l’exploite réellement — l’alerte existait, mais n’avait pas été traitée à temps.",
      syn: "Cyberwatch ; Tenable Nessus, Qualys, Rapid7", date: "2026-09-24" },
    { mot: "SIEM", emoji: "📡", type: "securite",
      def: "Corrèle les logs de tous les équipements de sécurité pour détecter les patterns d’une attaque coordonnée, plutôt que des alertes isolées et sans lien apparent.",
      ex: "Le SIEM reçoit en quelques secondes trois alertes séparées (firewall, WAF, EDR) et comprend qu’il s’agit d’une seule et même attaque en cours, ce que chaque outil pris isolément n’aurait pas vu.",
      syn: "Sekoia.io (hébergé OVH) ; Splunk, Microsoft Sentinel, IBM QRadar", date: "2026-09-24" },
    { mot: "SOC", emoji: "🧑‍💻", type: "securite",
      def: "Security Operations Center : équipe d’analystes (niveaux N1/N2/N3) qui traite au quotidien les alertes remontées par le SIEM.",
      ex: "Un analyste SOC de niveau N2 consulte les logs du bastion, confirme l’intrusion et escalade au N3, qui coupe l’accès réseau — attaque contenue en moins de 10 minutes.",
      syn: "Sopra Steria, Advens, Intrinsec ; IBM Security, Orange Cyberdefense, Atos", date: "2026-09-24" },
    { mot: "Bastion", emoji: "🚪", type: "securite",
      def: "Sas obligatoire par lequel tous les administrateurs doivent passer pour accéder à la production ; il trace et enregistre tout ce qui s’y passe.",
      ex: "En pleine investigation, l’analyste SOC consulte les logs du bastion et constate qu’aucun admin ne s’est connecté — ce qui confirme qu’il s’agit bien d’une intrusion externe.",
      syn: "Wallix Bastion (certifié ANSSI) ; CyberArk, BeyondTrust", date: "2026-09-24" },
    { mot: "NIS2", emoji: "🇪🇺", type: "securite",
      def: "Directive européenne qui impose des obligations de cybersécurité renforcées aux entités « essentielles » ou « importantes » (santé, énergie, transport, administration...) : segmentation réseau et MFA, détection/réponse aux incidents sous délais stricts (24h/72h), gestion du risque fournisseurs, plan de continuité testé.",
      ex: "Un hôpital, jugé entité « essentielle », doit désormais signaler tout incident de sécurité grave à l’ANSSI dans les 24h, puis fournir un rapport détaillé sous 72h.",
      syn: "ANSSI (autorité NIS2 en France)", date: "2026-09-24" },
    { mot: "AI Act", emoji: "⚖️", type: "securite",
      def: "Règlement européen (2024/1689) qui classe chaque système d’IA selon son niveau de risque (inacceptable, haut risque, risque limité, minimal) et impose des obligations proportionnées : traçabilité des décisions, supervision humaine obligatoire, documentation technique, tests de biais.",
      ex: "Un système d’IA qui trie automatiquement les alertes critiques en santé est classé « haut risque » et doit permettre à un humain de valider ou bloquer chaque décision — contrairement à un simple chatbot de FAQ, bien moins contraint.",
      syn: "CNIL (guides IA santé), HAS (référentiels IA médicale)", date: "2026-09-24" },
    { mot: "LDAP/AD vs IAM", emoji: "🗂️", type: "iam",
      def: "LDAP/Active Directory = l’annuaire, une base de données passive qui stocke qui existe, quel mot de passe, dans quel groupe. IAM (ex. Keycloak) = le chef d’orchestre : il interroge le LDAP mais fait bien plus (SSO, MFA, règles d’accès complexes RBAC/ABAC, fédération).",
      ex: "LDAP, c’est le fichier RH qui liste tous les employés. Keycloak, c’est le système de badge qui consulte ce fichier, émet les badges, gère les droits d’accès à chaque porte, et révoque les badges à la sortie.",
      syn: "", date: "2026-09-24" },
    { mot: "Annuaire (IAM)", emoji: "📇", type: "iam",
      def: "Registre central des utilisateurs : nom, rôle, service, type de contrat — la première brique de toute architecture IAM.",
      ex: "La DRH crée la fiche d’un nouveau médecin dans l’annuaire (FreeIPA) : cardiologue, service Urgences, CDD 6 mois.",
      syn: "FreeIPA", date: "2026-09-24" },
    { mot: "IGA", emoji: "⚙️", type: "iam",
      def: "Identity Governance & Administration : lit l’annuaire et décide automatiquement qui accède à quoi selon des règles métier ; crée, adapte et révoque les accès sans intervention manuelle.",
      ex: "Dès que la fiche du nouveau médecin apparaît dans l’annuaire, l’IGA lui attribue automatiquement l’accès à Nextcloud Urgences et au DPI cardiologie, mais lui refuse le bloc opératoire et la psychiatrie.",
      syn: "MidPoint", date: "2026-09-24" },
    { mot: "IDP (Identity Provider)", emoji: "🪪", type: "iam",
      def: "Vérifie le compte d’un utilisateur à la connexion et délivre un badge numérique (jeton) reconnu par tous les outils — c’est ce qui rend le SSO possible.",
      ex: "Le médecin se connecte une fois : l’IDP interroge l’annuaire, confirme le compte, demande le second facteur, puis il accède en une fois à sa messagerie, Nextcloud et son logiciel métier.",
      syn: "Keycloak", date: "2026-09-24" },
    { mot: "Générateur OTP", emoji: "🔢", type: "iam",
      def: "Second facteur d’authentification : génère un code à 6 chiffres, valable environ 30 secondes, à saisir en plus du mot de passe.",
      ex: "Après avoir saisi son mot de passe, l’utilisateur ouvre son application OTP et recopie le code à 6 chiffres affiché pour finaliser sa connexion.",
      syn: "FreeOTP", date: "2026-09-24" },
    { mot: "RBAC vs ABAC", emoji: "🎚️", type: "iam",
      def: "RBAC (Role-Based) : les droits sont liés à un rôle fixe — un médecin peut lire les dossiers patients, un comptable non. ABAC (Attribute-Based) : les droits dépendent d’attributs contextuels (qui, quoi, où, quand) — plus fin mais plus complexe.",
      ex: "En RBAC, tout médecin peut lire tout dossier patient. En ABAC, un médecin ne peut lire un dossier que si c’est son patient, depuis le réseau de l’hôpital, pendant ses heures de service — en santé, on combine souvent les deux.",
      syn: "", date: "2026-09-24" },
    { mot: "Prometheus", emoji: "📊", type: "observabilite",
      def: "Collecte et stocke les métriques chiffrées en temps réel (CPU, mémoire, latence) et déclenche des alertes si un seuil est dépassé — le capteur.",
      ex: "Prometheus détecte une chute de performance à 14h32 et déclenche une alerte automatique, avant même qu’un utilisateur ne s’en plaigne.",
      syn: "« Est-ce que ça va en ce moment ? »", date: "2026-09-24" },
    { mot: "Loki", emoji: "📓", type: "observabilite",
      def: "Collecte et stocke les logs texte des applications — le journal chronologique de ce qui s’est passé, en n’indexant que les métadonnées (léger et économique).",
      ex: "L’admin filtre les logs Loki sur la fenêtre 14h30-14h32 et découvre trois tentatives de connexion échouées qui ont saturé le serveur d’authentification.",
      syn: "« Que s’est-il passé, et pourquoi ? »", date: "2026-09-24" },
    { mot: "Grafana", emoji: "🖥️", type: "observabilite",
      def: "Ne stocke rien lui-même : se connecte à Prometheus, Loki et bien d’autres sources pour tout afficher dans une seule interface visuelle.",
      ex: "Grafana affiche dans un même écran la courbe CPU de Prometheus qui s’emballe et, juste à côté, les logs Loki de la même période — la corrélation prend 30 secondes au lieu d’une investigation manuelle.",
      syn: "« Comment tout visualiser en un coup d’œil ? »", date: "2026-09-24" },
    { mot: "Loki vs ELK", emoji: "🪶", type: "observabilite",
      def: "Deux façons de gérer les logs. ELK (Elasticsearch, Logstash, Kibana) indexe le texte complet des logs : recherche très puissante, mais gourmand en ressources. Loki n’indexe que les métadonnées (labels), beaucoup plus léger, pensé pour s’intégrer à Grafana et Kubernetes.",
      ex: "Pour chercher une chaîne de caractères précise dans des millions de logs, ELK est plus puissant ; pour surveiller un cluster Kubernetes à moindre coût, Loki suffit largement.",
      syn: "", date: "2026-09-24" },
    { mot: "SRE", emoji: "🎯", type: "observabilite",
      def: "Site Reliability Engineering : discipline née chez Google qui applique des méthodes d’ingénierie logicielle aux problèmes d’exploitation IT — la mise en œuvre concrète et mesurable de la culture DevOps.",
      ex: "Là où le DevOps dit « rapprochons Dev et Ops », le SRE répond « voici les indicateurs précis (SLI/SLO/error budget) qui nous diront si on y arrive ».",
      syn: "", date: "2026-09-24" },
    { mot: "SLI / SLO / SLA", emoji: "📐", type: "observabilite",
      def: "SLI (Indicator) : une métrique mesurée, ex. le taux de disponibilité réel. SLO (Objective) : l’objectif interne visé sur ce SLI, ex. 99,9 %. SLA (Agreement) : l’engagement contractuel envers le client, généralement moins strict que le SLO.",
      ex: "Le SLI mesure 99,95 % de disponibilité ce mois-ci ; l’équipe visait un SLO de 99,9 % (objectif atteint) ; le contrat client (SLA) ne promettait que 99,5 % — une marge de sécurité assumée.",
      syn: "", date: "2026-09-24" },
    { mot: "Error budget", emoji: "💰", type: "observabilite",
      def: "La marge d’erreur tolérée (déduite du SLO) avant de devoir arbitrer entre déployer de nouvelles fonctionnalités et se concentrer sur la stabilité.",
      ex: "Si le SLO autorise 0,1 % d’indisponibilité par mois et que ce budget est déjà consommé à la moitié du mois, l’équipe gèle les nouvelles fonctionnalités pour se concentrer sur la fiabilité.",
      syn: "", date: "2026-09-24" },
    { mot: "PCA vs PRA", emoji: "🆘", type: "continuite",
      def: "PCA (Plan de Continuité d’Activité) : infrastructure redondante active en permanence, deux datacenters qui tournent simultanément — zéro interruption tolérable, mais très cher. PRA (Plan de Reprise d’Activité) : un site de secours qui dort et se réveille en cas de catastrophe — quelques heures d’arrêt acceptées, coût bien inférieur.",
      ex: "À l’hôpital, le bloc opératoire et la réanimation ont besoin d’un PCA (zéro interruption tolérable) ; la gestion RH peut se permettre un PRA (quelques heures d’arrêt acceptables) — une décision économique et métier, pas uniquement technique.",
      syn: "", date: "2026-09-24" },
    { mot: "Fork vs Upstream", emoji: "🍴", type: "opensource",
      def: "Un projet open source est une recette de cuisine partagée publiquement. Le dépôt upstream (« amont ») est la version officielle, maintenue par la communauté. Un fork : quelqu’un copie la recette et la modifie de son côté, sans repartager — sa version diverge et lui seul l’entretient.",
      ex: "Contribuer en upstream, c’est proposer ses améliorations au livre communautaire : si la communauté valide, tout le monde en profite et personne n’a à maintenir une version à part.",
      syn: "", date: "2026-09-24" },
    { mot: "CMDB", emoji: "🗃️", type: "opensource",
      def: "Configuration Management Database : base de données qui référence tous les actifs IT (serveurs, applications, licences, équipements réseau) ainsi que leurs relations de dépendance entre eux.",
      ex: "Avant de couper un serveur pour maintenance, on consulte la CMDB pour savoir quelles applications en dépendent et qui serait impacté.",
      syn: "GLPI (open source, France), iTop (PME/ESN) ; ServiceNow, BMC Helix (propriétaires)", date: "2026-09-24" },
    { mot: "Confluence", emoji: "📘", type: "opensource",
      def: "Outil de documentation collaborative — un wiki d’entreprise structuré en espaces et pages, souvent utilisé avec Jira, avec historique de versions et droits d’accès par espace.",
      ex: "L’équipe centralise dans Confluence la documentation technique de l’infrastructure, les comptes rendus de projet et les procédures d’astreinte.",
      syn: "Atlassian", date: "2026-09-24" },
    { mot: "Debian vs Ubuntu", emoji: "🐧", type: "systemes",
      def: "Deux distributions Linux — des « versions » de Linux packagées et prêtes à l’emploi, comme il existe Windows 10 et Windows 11. Debian est la version communautaire, stable et minimaliste. Ubuntu est construite dessus, plus accessible, avec support commercial.",
      ex: "Sur un poste hospitalier, cela ressemble à un bureau classique, mais tournant sous Linux au lieu de Windows.",
      syn: "", date: "2026-09-24" },
    { mot: "WOPI", emoji: "📄", type: "systemes",
      def: "Web Application Open Platform Interface : protocole qui permet à une application web d’ouvrir et d’éditer des fichiers Office sans les télécharger.",
      ex: "Un utilisateur clique sur un .docx stocké dans Nextcloud : il s’ouvre directement dans un éditeur en ligne (OnlyOffice, Collabora), sans jamais passer par Word installé localement.",
      syn: "", date: "2026-09-24" },
    { mot: "LDAP (protocole)", emoji: "📖", type: "systemes",
      def: "Protocole standardisé pour interroger un annuaire : c’est le « langage » que parlent les annuaires pour répondre à « cet utilisateur existe-t-il et son mot de passe est-il correct ? »",
      ex: "Un utilisateur tape son login sur un PC d’hôpital : le système envoie une requête LDAP pour vérifier qu’il existe et récupérer ses droits.",
      syn: "", date: "2026-09-24" },
    { mot: "OIDC / SAML", emoji: "🔑", type: "systemes",
      def: "Deux protocoles de fédération d’identité qui permettent à une application de déléguer l’authentification à un fournisseur d’identité plutôt que de gérer elle-même les mots de passe — ce qui rend le SSO possible. SAML : plus ancien, basé sur du XML. OIDC : plus récent, basé sur OAuth2/JSON, plus léger.",
      ex: "Une application web moderne délègue la connexion à Keycloak via OIDC ; une application d’entreprise historique fait la même chose, mais via SAML.",
      syn: "", date: "2026-09-24" },
    { mot: "SMTP", emoji: "✉️", type: "systemes",
      def: "Protocole qui transporte les emails d’un serveur à un autre.",
      ex: "Un patient reçoit un email automatique « Votre rendez-vous du 12 mai est confirmé » : c’est Postfix, le serveur SMTP, qui a acheminé cet email depuis l’application hospitalière jusqu’à sa boîte mail.",
      syn: "Postfix", date: "2026-09-24" },
    { mot: "LangChain", emoji: "🔗", type: "ia",
      def: "Framework (bibliothèque de code Python/JS) qui fournit des briques toutes faites pour construire un pipeline GenAI : connexion à un LLM, gestion de la mémoire, recherche RAG, appel d’outils, enchaînement d’étapes.",
      ex: "Plutôt que de recoder à la main la connexion au modèle et la recherche documentaire, un développeur assemble ces briques LangChain pour construire son assistant IA en quelques jours.",
      syn: "", date: "2026-09-24" },
    { mot: "Grounding", emoji: "⚓", type: "ia",
      def: "Le fait de forcer un modèle d’IA à ancrer sa réponse dans une source documentaire réelle et vérifiable, plutôt que de la générer « de mémoire » à partir de ses probabilités internes.",
      ex: "Littéralement « mettre les pieds au sol » : le modèle ne répond que s’il peut pointer vers un passage source concret — c’est le principe qui sous-tend le RAG (Retrieval-Augmented Generation).",
      syn: "RAG (Retrieval-Augmented Generation)", date: "2026-09-24" }
  ];

  var TYPE_LABELS = {
    devops: "DevOps & CI/CD", virtu: "Virtualisation & Orchestration", securite: "Sécurité",
    iam: "IAM", observabilite: "Observabilité", continuite: "Continuité d’activité",
    opensource: "Open Source & Gestion IT", systemes: "Systèmes & Protocoles", ia: "IA Générative"
  };
  var GROUP_LABELS = {
    tous: "Tous", devops: "DevOps", virtu: "Virtu & Orchestration", securite: "Sécurité",
    iam: "IAM", observabilite: "Observabilité", continuite: "Continuité", opensource: "Open Source",
    systemes: "Systèmes", ia: "IA"
  };
  var GROUP_OF = {
    devops: "devops", virtu: "virtu", securite: "securite", iam: "iam",
    observabilite: "observabilite", continuite: "continuite", opensource: "opensource",
    systemes: "systemes", ia: "ia"
  };
  // Le carnet réutilise le même moteur que le carnet de vocabulaire ; ce tableau
  // (sous-catégories de "blagues" là-bas) reste référencé par du code partagé —
  // vide ici, il ne fait jamais rien pour ce jeu de fiches.
  var BLAGUE_TYPES = [];

  BASE_ENTRIES.forEach(function (e, i) { e.id = i; e.group = GROUP_OF[e.type]; });
